### PR TITLE
Support multiple datetime formats

### PR DESCRIPTION
**Pull request by nkottary**

### CODE REVIEW

**Comment by aviks** [comment]
Ping @quinnj . Thoughts on this?

**Comment by quinnj** [comment]
Can I convince you to switch to JSON3? It supports specifying keyword arguments per struct field; so it's even more flexible than the solution here. Happy to merge this if you need, but note that JSON2 is unmaintained/soon to be archived, so I'm really happy to help people move over to JSON3.

**Comment by aviks** [comment]
Yes, there is no doubt we need to move to JSON3, but the packages that depend on this are not [terribly well maintained](https://github.com/christopher-dG/GitForge.jl/pull/14#issuecomment-624089925) either, so I think we need some breathing room to make the switch. So it'd be really great if this can be merged and tagged as a last gasp. I realise the solution here is a bit of a hack, but if we're not going to spend too much time on this package, this might be OK.

**Comment by nkottary** [comment]
@quinnj  Can you register a new version of this package?

**Pull request merged**
